# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Uh"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/digitaleinitiativen/"
tags = ["bootstrap", "jquery", "responsive"]
features = ["", ""]
min_version = 0.14

[author]
  name = "Johannes Moser"
  homepage = "https://joemoe.at"